# Generated by Django 6.0.7 on 2026-07-16 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('pdf_file', models.FileField(upload_to='books/pdfs/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/covers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('file_size_mb', models.FloatField(default=0.0)),
                ('is_approved', models.BooleanField(default=False)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
