from django.shortcuts import render


def home(request):
    ai_tools = [
        {
            'name': 'Google Gemini',
            'icon': '🔮',
            'color': '#4285F4',
            'gradient': 'linear-gradient(135deg, #4285F4, #0F9D58)',
            'description': 'Google\'s most capable AI model with multimodal understanding.',
            'features': ['Multimodal AI', 'Code Generation', 'Deep Research', 'Real-time Data'],
            'url': 'https://gemini.google.com',
            'category': 'Language Model',
        },
        {
            'name': 'ChatGPT',
            'icon': '🤖',
            'color': '#10A37F',
            'gradient': 'linear-gradient(135deg, #10A37F, #1a7f64)',
            'description': 'OpenAI\'s revolutionary conversational AI powering millions worldwide.',
            'features': ['GPT-4o', 'DALL·E 3', 'Code Interpreter', 'Plugins'],
            'url': 'https://chat.openai.com',
            'category': 'Language Model',
        },
        {
            'name': 'Claude',
            'icon': '⚡',
            'color': '#CC785C',
            'gradient': 'linear-gradient(135deg, #CC785C, #a85e45)',
            'description': 'Anthropic\'s AI assistant focused on safety and helpfulness.',
            'features': ['200K Context', 'Document Analysis', 'Safe AI', 'Long Coding Tasks'],
            'url': 'https://claude.ai',
            'category': 'Language Model',
        },
        {
            'name': 'Midjourney',
            'icon': '🎨',
            'color': '#7C3AED',
            'gradient': 'linear-gradient(135deg, #7C3AED, #5B21B6)',
            'description': 'World-class AI image generator creating stunning, artistic visuals.',
            'features': ['Photorealistic Art', 'Style Transfer', 'Variations', 'Discord Bot'],
            'url': 'https://midjourney.com',
            'category': 'Image Generation',
        },
        {
            'name': 'Suno AI',
            'icon': '🎵',
            'color': '#EC4899',
            'gradient': 'linear-gradient(135deg, #EC4899, #BE185D)',
            'description': 'Create full songs with vocals, instruments, and lyrics using AI.',
            'features': ['AI Vocals', 'Music Genres', 'Lyrics Gen', 'Full Songs'],
            'url': 'https://suno.com',
            'category': 'Music Generation',
        },
        {
            'name': 'Runway ML',
            'icon': '🎬',
            'color': '#F59E0B',
            'gradient': 'linear-gradient(135deg, #F59E0B, #D97706)',
            'description': 'Next-gen AI video creation and editing platform for creators.',
            'features': ['Gen-3 Video', 'Motion Brush', 'Inpainting', 'Video Effects'],
            'url': 'https://runwayml.com',
            'category': 'Video Generation',
        },
    ]

    stats = [
        {'label': 'AI Tools Featured', 'value': '50+', 'icon': '🛠️'},
        {'label': 'Use Cases Covered', 'value': '100+', 'icon': '🎯'},
        {'label': 'AI Models', 'value': '25+', 'icon': '🧠'},
        {'label': 'Active Users', 'value': '10M+', 'icon': '👥'},
    ]

    return render(request, 'core/home.html', {'ai_tools': ai_tools, 'stats': stats})


def usecases(request):
    use_cases = [
        {
            'category': 'AI Music',
            'emoji': '🎵',
            'color': '#EC4899',
            'glow': 'rgba(236,72,153,0.3)',
            'description': 'Create original songs, beats, and soundtracks with AI — no musical training needed.',
            'tools': [
                {'name': 'Suno AI', 'desc': 'Full songs with vocals', 'url': 'https://suno.com'},
                {'name': 'Udio', 'desc': 'High-quality music gen', 'url': 'https://udio.com'},
                {'name': 'MusicLM', 'desc': 'Google\'s music AI', 'url': 'https://aitestkitchen.withgoogle.com'},
                {'name': 'Stable Audio', 'desc': 'Stems & sound design', 'url': 'https://stableaudio.com'},
            ],
            'examples': ['Lo-fi study beats', 'Pop song with lyrics', 'Epic film score', 'Custom jingles'],
        },
        {
            'category': 'AI Video',
            'emoji': '🎬',
            'color': '#F59E0B',
            'glow': 'rgba(245,158,11,0.3)',
            'description': 'Generate, edit, and transform videos with cutting-edge AI models.',
            'tools': [
                {'name': 'Runway Gen-3', 'desc': 'Cinematic video AI', 'url': 'https://runwayml.com'},
                {'name': 'Pika Labs', 'desc': 'Text-to-video magic', 'url': 'https://pika.art'},
                {'name': 'Sora (OpenAI)', 'desc': 'Hyper-realistic video', 'url': 'https://openai.com/sora'},
                {'name': 'Kling AI', 'desc': 'Fast video generation', 'url': 'https://klingai.com'},
            ],
            'examples': ['Product ads', 'Short films', 'Social reels', 'Explainer videos'],
        },
        {
            'category': 'AI Images',
            'emoji': '🖼️',
            'color': '#7C3AED',
            'glow': 'rgba(124,58,237,0.3)',
            'description': 'Generate photorealistic and artistic images from text descriptions.',
            'tools': [
                {'name': 'Midjourney', 'desc': 'Best quality images', 'url': 'https://midjourney.com'},
                {'name': 'DALL·E 3', 'desc': 'OpenAI image gen', 'url': 'https://openai.com/dall-e-3'},
                {'name': 'Stable Diffusion', 'desc': 'Open-source powerhouse', 'url': 'https://stability.ai'},
                {'name': 'Adobe Firefly', 'desc': 'Commercial-safe art', 'url': 'https://firefly.adobe.com'},
            ],
            'examples': ['Marketing assets', 'Character design', 'Product mockups', 'Digital art'],
        },
        {
            'category': 'AI Chat & Research',
            'emoji': '💬',
            'color': '#10A37F',
            'glow': 'rgba(16,163,127,0.3)',
            'description': 'Have intelligent conversations, research topics, and get expert-level answers.',
            'tools': [
                {'name': 'ChatGPT', 'desc': 'OpenAI\'s flagship chat', 'url': 'https://chat.openai.com'},
                {'name': 'Google Gemini', 'desc': 'Google\'s powerful AI', 'url': 'https://gemini.google.com'},
                {'name': 'Claude', 'desc': 'Anthropic\'s safe AI', 'url': 'https://claude.ai'},
                {'name': 'Perplexity', 'desc': 'AI-powered search', 'url': 'https://perplexity.ai'},
            ],
            'examples': ['Deep research', 'Essay writing', 'Q&A sessions', 'Brainstorming'],
        },
        {
            'category': 'AI Code',
            'emoji': '💻',
            'color': '#3B82F6',
            'glow': 'rgba(59,130,246,0.3)',
            'description': 'Write, debug, and optimize code 10x faster with AI coding assistants.',
            'tools': [
                {'name': 'GitHub Copilot', 'desc': 'In-editor AI coding', 'url': 'https://github.com/features/copilot'},
                {'name': 'Cursor', 'desc': 'AI-first code editor', 'url': 'https://cursor.sh'},
                {'name': 'CodeLlama', 'desc': 'Open-source code AI', 'url': 'https://ai.meta.com/llama/'},
                {'name': 'Replit AI', 'desc': 'Build apps in browser', 'url': 'https://replit.com'},
            ],
            'examples': ['Auto-completion', 'Bug fixing', 'Code review', 'App generation'],
        },
        {
            'category': 'AI Voice & Audio',
            'emoji': '🔊',
            'color': '#06B6D4',
            'glow': 'rgba(6,182,212,0.3)',
            'description': 'Clone voices, generate speech, and create podcast-quality audio with AI.',
            'tools': [
                {'name': 'ElevenLabs', 'desc': 'Realistic voice cloning', 'url': 'https://elevenlabs.io'},
                {'name': 'Murf AI', 'desc': 'Professional voiceovers', 'url': 'https://murf.ai'},
                {'name': 'Descript', 'desc': 'Audio editing with AI', 'url': 'https://descript.com'},
                {'name': 'Whisper', 'desc': 'Speech-to-text AI', 'url': 'https://openai.com/research/whisper'},
            ],
            'examples': ['Podcast voices', 'Audiobooks', 'Video narration', 'Translation'],
        },
        {
            'category': 'AI Writing',
            'emoji': '✍️',
            'color': '#F97316',
            'glow': 'rgba(249,115,22,0.3)',
            'description': 'Draft articles, emails, scripts, and marketing copy instantly.',
            'tools': [
                {'name': 'Jasper AI', 'desc': 'Marketing copy gen', 'url': 'https://jasper.ai'},
                {'name': 'Copy.ai', 'desc': 'AI copywriting', 'url': 'https://copy.ai'},
                {'name': 'Notion AI', 'desc': 'Smart docs & notes', 'url': 'https://notion.so'},
                {'name': 'Grammarly AI', 'desc': 'AI writing assistant', 'url': 'https://grammarly.com'},
            ],
            'examples': ['Blog posts', 'Ad copy', 'Email sequences', 'Social media'],
        },
        {
            'category': 'AI Agents',
            'emoji': '🤖',
            'color': '#8B5CF6',
            'glow': 'rgba(139,92,246,0.3)',
            'description': 'Autonomous AI agents that plan, execute, and complete complex tasks.',
            'tools': [
                {'name': 'AutoGPT', 'desc': 'Autonomous task agent', 'url': 'https://github.com/Significant-Gravitas/AutoGPT'},
                {'name': 'LangChain', 'desc': 'AI agent framework', 'url': 'https://langchain.com'},
                {'name': 'CrewAI', 'desc': 'Multi-agent teams', 'url': 'https://crewai.com'},
                {'name': 'n8n AI', 'desc': 'AI workflow automation', 'url': 'https://n8n.io'},
            ],
            'examples': ['Web research', 'Data analysis', 'Email automation', 'Task planning'],
        },
    ]
    return render(request, 'core/usecases.html', {'use_cases': use_cases})


def explore(request):
    agents = [
        {
            'name': 'Google Gemini',
            'icon': '🔮',
            'company': 'Google DeepMind',
            'color': '#4285F4',
            'version': 'Gemini 2.0',
            'context': '2M tokens',
            'multimodal': True,
            'free_tier': True,
            'api': True,
            'best_for': 'Research & coding',
            'rating': 4.8,
            'url': 'https://gemini.google.com',
            'specialties': ['Multimodal', 'Long Context', 'Google Search', 'Live API'],
            'pricing': 'Free + Pro $20/mo',
        },
        {
            'name': 'ChatGPT',
            'icon': '🤖',
            'company': 'OpenAI',
            'color': '#10A37F',
            'version': 'GPT-4o',
            'context': '128K tokens',
            'multimodal': True,
            'free_tier': True,
            'api': True,
            'best_for': 'General purpose',
            'rating': 4.9,
            'url': 'https://chat.openai.com',
            'specialties': ['GPT-4o', 'DALL·E 3', 'Code Execution', 'Voice Mode'],
            'pricing': 'Free + Plus $20/mo',
        },
        {
            'name': 'Claude',
            'icon': '⚡',
            'company': 'Anthropic',
            'color': '#CC785C',
            'version': 'Claude 3.5 Sonnet',
            'context': '200K tokens',
            'multimodal': True,
            'free_tier': True,
            'api': True,
            'best_for': 'Long documents & safety',
            'rating': 4.7,
            'url': 'https://claude.ai',
            'specialties': ['Largest Context', 'Document Analysis', 'Safe Outputs', 'Long Coding'],
            'pricing': 'Free + Pro $20/mo',
        },
        {
            'name': 'Perplexity',
            'icon': '🔍',
            'company': 'Perplexity AI',
            'color': '#20B2AA',
            'version': 'Llama + GPT-4',
            'context': '32K tokens',
            'multimodal': False,
            'free_tier': True,
            'api': True,
            'best_for': 'Real-time research',
            'rating': 4.5,
            'url': 'https://perplexity.ai',
            'specialties': ['Real-time Search', 'Citations', 'No Hallucination', 'Pro Search'],
            'pricing': 'Free + Pro $20/mo',
        },
        {
            'name': 'Copilot',
            'icon': '💻',
            'company': 'GitHub / Microsoft',
            'color': '#6E40C9',
            'version': 'GPT-4 Turbo',
            'context': '64K tokens',
            'multimodal': True,
            'free_tier': True,
            'api': True,
            'best_for': 'Coding & debugging',
            'rating': 4.6,
            'url': 'https://github.com/features/copilot',
            'specialties': ['Code Completion', 'PR Reviews', 'Multi-Language', 'IDE Integration'],
            'pricing': 'Free + Pro $10/mo',
        },
        {
            'name': 'Grok',
            'icon': '𝕏',
            'company': 'xAI (Elon Musk)',
            'color': '#E7E7E7',
            'version': 'Grok-2',
            'context': '128K tokens',
            'multimodal': True,
            'free_tier': False,
            'api': True,
            'best_for': 'Real-time X data',
            'rating': 4.3,
            'url': 'https://x.ai',
            'specialties': ['Real-time X Posts', 'Unfiltered Answers', 'Image Gen', 'Fun Mode'],
            'pricing': 'X Premium $8/mo',
        },
    ]

    workflow_steps = [
        {'step': '01', 'title': 'Define Your Task', 'desc': 'Clearly describe what you want the AI to accomplish — be specific and detailed.', 'icon': '🎯'},
        {'step': '02', 'title': 'Choose the Right AI', 'desc': 'Select the AI tool best suited for your task type — chat, code, image, video, or audio.', 'icon': '🔮'},
        {'step': '03', 'title': 'Craft Your Prompt', 'desc': 'Write a detailed prompt. Include context, tone, format, and examples for best results.', 'icon': '✍️'},
        {'step': '04', 'title': 'Iterate & Refine', 'desc': 'Review the output, give feedback, and refine until you get exactly what you need.', 'icon': '🔄'},
        {'step': '05', 'title': 'Deploy & Automate', 'desc': 'Use APIs or automation tools to integrate AI into your workflow at scale.', 'icon': '🚀'},
    ]

    return render(request, 'core/explore.html', {'agents': agents, 'workflow_steps': workflow_steps})
